package main.java.tothonderd.tottwintig;

/**
 * Created by AL13685 on 15-5-2018.
 */

//The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:
//
//        1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...
//
//        Let us list the factors of the first seven triangle numbers:
//
//        1: 1
//        3: 1,3
//        6: 1,2,3,6
//        10: 1,2,5,10
//        15: 1,3,5,15
//        21: 1,3,7,21
//        28: 1,2,4,7,14,28
//        We can see that 28 is the first triangle number to have over five divisors.
//
//        What is the value of the first triangle number to have over five hundred divisors?
public class Opdracht12 {

    public static void main(String[] args) {
        int numberToTest = 1;
        int triangleNumber = 1;

        while (true) {
            int counter = 0;
            int highestDevider = Integer.MAX_VALUE;

            for (int i = 1; i <= numberToTest && i < highestDevider; i++) {
                if (numberToTest % i == 0) {
                    highestDevider = numberToTest / i;
                    counter++;
                    if (highestDevider != i) {
                        counter++;
                    }
                }
            }

            if (counter < 500) {
                triangleNumber = triangleNumber + 1;
                numberToTest = numberToTest + triangleNumber;

            } else {
                break;
            }
        }
        System.out.println(numberToTest);
    }
}
