package main.java;

import java.util.ArrayList;
import java.util.List;

/**
 * Created by AL13685 on 9-5-2018.
 */

//Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
//        1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
//        By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
public class Opdracht2 {

    private static List<Integer> fibonacci = new ArrayList<>();

    public static void main(String[] args) {
        fibonacci.add(1);
        fibonacci.add(2);
        addNumber();
    }

    private static void addNumber() {
        int laatsteNummer = fibonacci.get(fibonacci.size() - 1);
        int eenALaatsteNummer = fibonacci.get(fibonacci.size() - 2);
        int nieuwNummer = laatsteNummer + eenALaatsteNummer;

        if (nieuwNummer <= 4000000) {
            fibonacci.add(nieuwNummer);
            addNumber();
        } else {
            findEvenNumbers();
        }
    }

    private static void findEvenNumbers() {
        int answer = 0;
        for (int i : fibonacci) {
            if ( i % 2 == 0) {
                answer = answer  + i;
            }
        }
        System.out.println(answer);
    }


}
